### PR TITLE
Add simple clock widget

### PR DESCRIPTION
**Pull request by InfoSec812**
This adds a VERY simple clock widget. Shows the current time in the brower's time zone.

### CODE REVIEW

**Comment by ganncamp** [comment]
Hi @InfoSec812, this plugin is no longer a priority for me. Would you like to become the maintainer?

**Comment by InfoSec812** [comment]
Hi Ann.... It's not a huge priority for me either, but I could certainly look after it for you... I might be able to contribute to resolving some of the open issues over the next 2-3 months...

**Comment by ganncamp** [comment]
I've requested permissions for you. I'll let you know when they're granted. Then you can merge your own PR! :)

**Comment by InfoSec812** [comment]
With the exception that the Travis-CI settings are wrong right now, so the
build it failing! Oh noes! :)

Deven

**Comment by ganncamp** [comment]
Yeah, I'm working on that. BTW, you have perms, but let me work through this travis stuff before you merge.

**Comment by InfoSec812** [comment]
Ann,

   OK, thanks! Let me know if I can help with the Travis CI issues.

Deven

**Comment by ganncamp** [comment]
Hi Deven,

Master's fixed up now & you should be good to go.

**Comment by InfoSec812** [comment]
OK, let me run the build through my Travis account and be sure it builds
and then I will merge my PR...

Thanks Ann!

Deven

**Pull request merged**
